yocto_recipe: use ROS_PYTHON_VERSION 2 only for melodic
ros-infrastructure/superflore pull request #280
Opened 2020-11-06 00:05 UTC by shr-project

* noetic should use 3

Signed-off-by: Martin Jansa <martin.jansa@lge.com>

2020-11-06 10:11 UTC, shr-project commented
@allenh1 @herb-kuta-lge Please review and merge

2020-12-05 03:07 UTC, herb-kuta-lge requested changes

2020-12-05 03:07 UTC, herb-kuta-lge commented on superflore/generators/bitbake/yocto_recipe.py
> +                err("package pkg_name either doesn't have <export><build_type>"
`"package pkg_name ..."` -> `"Package {0} ... ".format(pkg_name)`

2020-12-05 03:07 UTC, herb-kuta-lge commented on superflore/generators/bitbake/yocto_recipe.py
> +                yoctoRecipe._get_ros_version(distro.name) == 1 \
Commit body: `get_ros_version` -> `_get_ros_version()`

2020-12-05 03:07 UTC, herb-kuta-lge commented on setup.py
> +    'catkin_pkg >= 0.4.10',
Commit summary: `get_build_type` -> `get_build_type()`

Commit body: `0.4.10 verion` -> `v0.4.10`

2020-12-05 12:55 UTC, shr-project commented on superflore/generators/bitbake/yocto_recipe.py
> +                if distro == 'melodic':
ros-generate-{cache,recipes}.sh does abort.

2020-12-08 20:19 UTC, shr-project commented
Depends on https://github.com/ros-infrastructure/superflore/pull/281 now

2020-12-10 18:57 UTC, allenh1 submitted a review, later dismissed
lgtm

2020-12-10 19:14 UTC, allenh1 commented
@herb-kuta-lge please take a look at this one when you can

2020-12-10 20:57 UTC, herb-kuta-lge commented on superflore/generators/bitbake/yocto_recipe.py
> +                if distro == 'melodic':
OK, then at least document that ROS 1 distros prior to *melodic* are not supported in `README.md`:
```
  --ros-distro ROS_DISTRO
                        regenerate packages for the specified distro
```
Append `; ROS 1 distros prior to "melodic" are not supported` (in two places).

2020-12-10 22:03 UTC, herb-kuta-lge commented on superflore/generators/bitbake/yocto_recipe.py
> +                yoctoRecipe._get_ros_version(distro.name) == 1 \
There's another one to change in the commit body of 100feaea0e34ff469fc429345a7f061fcd49b458 .

2020-12-10 22:07 UTC, herb-kuta-lge commented on setup.py
> +    'catkin_pkg >= 0.4.10',
Commit summary: get_build_type -> get_build_type() in a409be822b8e983dff5af518bb5a61c21a18ce0a (just a nit, obviously).

2020-12-10 22:09 UTC, herb-kuta-lge requested changes
I've unresolved 3 of the conversations.

2020-12-11 00:42 UTC, shr-project commented on superflore/generators/bitbake/yocto_recipe.py
> +                if distro == 'melodic':
Which 2 places? This section of README.md is matching with the -h output.

2020-12-11 00:43 UTC, shr-project commented
Please DON'T SQUASH the commits when merging, it will be impossible to review and understand the commits after they are squashed.

2020-12-11 02:20 UTC, herb-kuta-lge commented on superflore/generators/bitbake/yocto_recipe.py
> +                if distro == 'melodic':
> Which 2 places?

There aren't (which is why I edited my comment :-) ). But I did forget that this section is the output from `-h`. So instead, add this note to the **Common Usage:** section after `The --ros-distro flag must be supplied.`: `ROS 1 distros prior to "melodic" are not supported`.

2020-12-11 02:27 UTC, herb-kuta-lge requested changes
Unresolved 1 conversation.

2020-12-11 15:43 UTC, herb-kuta-lge submitted a review, later dismissed
LGTM.

2020-12-11 22:56 UTC, allenh1 approved these changes

2020-12-12 00:22 UTC, herb-kuta-lge approved these changes

2020-12-12 23:56 UTC, merged